### ISSUE TITLE
Ive notice all buildtime of hugo with tailwind is pretty damn slow

### ISSUE THREAD

**Issue by codeitlikemiley** [bep/hugo-starter-tailwind-basic#2]
Hi, this has been issue with tailwind itself...
but there is a way to speed up buildtime, at the cost of not being able to use @apply

but i think the trade off is pretty good, since you dont usually use it
me personally...

https://nystudio107.com/blog/speeding-up-tailwind-css-builds

Ive notice the buildtime on this new starter app is 3.6 secs which is slow compare to other hugo site
which is  below 500 ms without all the added stuffs...

Quck question, is esbuild the compiler being used to process css?
thats the fastest compiler yet tailwind is so slow...
Been trying to cut down the cold start boot time in my main project from 11secs now at 6 secs...
significant increase...
i think all starter template should be at least around 200ms from scratch...

**Comment by bep** [comment]
So, the idea of Tailwind is that most of your style editing is going to happen in the templates, which is fast. As to the Tailwind compile, you need to take it up with ... them.
