### ISSUE TITLE
Difference between this and hugo-theme-tailwindcss-starter?

### ISSUE THREAD

**Issue by adamjohnson** [bep/hugo-starter-tailwind-basic#3]
Just curious what the difference between this Starter and [hugo-theme-tailwindcss-starter](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter)? 

I noticed this one is newer and has the config files in a different location. Does this repository use new features in Hugo that would make this a better Starter?

Thanks in advance for any input you're willing to share.

**Comment by bep** [comment]
You need to ask him that, not me.
